apiVersion: v1
kind: Namespace
metadata:
  name: test
---
apiVersion: v1
kind: Pod
metadata:
  name: allowed-pod
  namespace: test
spec:
  containers:
    - name: approved-container
      image: docker.io/library/nginx:latest
---
apiVersion: v1
kind: Pod
metadata:
  name: blocked-pod
  namespace: test
spec:
  containers:
    - name: unapproved-container
      image: public.ecr.aws/amazonlinux/amazonlinux:latest
      command: ["/bin/sh", "-c"]
      args: ["sleep infinity"]